apiVersion: v1
kind: Pod
metadata:
  name: python-test
spec:
  restartPolicy: OnFailure
  runtimeClassName: seeweb-nvidia-1xa6000
  imagePullSecrets:
    - name: ghcr-secret
  containers:
  - name: nvidia
    image: "ghcr.io/narden91/k8s_test:sha-6a6213e"
    command: ["python"]
    args: ["main.py"]
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: "1"
    envFrom:
      - secretRef:
          name: s3-secrets
