apiVersion: v1
kind: Pod
metadata:
  name: python-pod
spec:
  restartPolicy: OnFailure
  runtimeClassName: seeweb-nvidia-1xa6000
  containers:
  - name: nvidia
    image: "nvidia/cuda:11.8.0-runtime-ubuntu22.04"
    command: ["python3"]
    args: ["/home/test/main.py"]
    imagePullPolicy: Always
    volumeMounts:
    - name: code-volume
      mountPath: /home/test
    - name: results-volume
      mountPath: /home/test/results
  volumes:
  - name: code-volume
    hostPath:
      path: /home/test
      type: Directory
  - name: results-volume
    hostPath:
      path: /home/test/results
      type: DirectoryOrCreate